# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/model.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'protos/model.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12protos/model.proto\"4\n\x0ePredictRequest\x12\x10\n\x08\x66\x65\x61ture1\x18\x01 \x01(\x02\x12\x10\n\x08\x66\x65\x61ture2\x18\x02 \x01(\x02\"4\n\x0fPredictResponse\x12\x12\n\nprediction\x18\x01 \x01(\t\x12\r\n\x05proba\x18\x02 \x01(\t\"\x07\n\x05\x45mpty\"7\n\x0eHealthResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x15\n\rmodel_version\x18\x02 \x01(\t2d\n\x11PredictionService\x12,\n\x07Predict\x12\x0f.PredictRequest\x1a\x10.PredictResponse\x12!\n\x06Health\x12\x06.Empty\x1a\x0f.HealthResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.model_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PREDICTREQUEST']._serialized_start=22
  _globals['_PREDICTREQUEST']._serialized_end=74
  _globals['_PREDICTRESPONSE']._serialized_start=76
  _globals['_PREDICTRESPONSE']._serialized_end=128
  _globals['_EMPTY']._serialized_start=130
  _globals['_EMPTY']._serialized_end=137
  _globals['_HEALTHRESPONSE']._serialized_start=139
  _globals['_HEALTHRESPONSE']._serialized_end=194
  _globals['_PREDICTIONSERVICE']._serialized_start=196
  _globals['_PREDICTIONSERVICE']._serialized_end=296
# @@protoc_insertion_point(module_scope)
